### ISSUE TITLE
Open files in a non-blocking manner

### ISSUE THREAD

**Issue by kirusfg** [Byron/open-rs#46] opened 2022-06-09 14:10 UTC
My use case for this feature is quite specific. I am making a book/article organizer, and would like to be able to open the files via CLI and TUI. 

Currently, opening files like PDF prevents the program from exiting because the child process (in my case, a PDF reader `zathura`) is awaited by the parent [here](https://github.com/Byron/open-rs/blob/bf6e99cb578cd3c90eed3ff4fddd712b26982e21/src/lib.rs#L204). This would affect the future TUI of my program even more, making it unresponsive.

Ideally, I would like to have something like `open::that_and_forget`:
```rust
pub fn that_and_forget<T: AsRef<OsStr>>(path: T) -> Result {
    let path = path.as_ref();
    let open_handlers = [
        ("xdg-open", &[path] as &[_]),
        ("gio", &[OsStr::new("open"), path]),
        ("gnome-open", &[path]),
        ("kde-open", &[path]),
        ("wslview", &[&wsl_path(path)]),
    ];

    let mut unsuccessful = None;
    let mut io_error = None;

    for (command, args) in &open_handlers {
        let result = Command::new(command).args(*args).spawn();

        match result {
            Ok(_) => return Ok(()),
            Err(err) => io_error = io_error.or(Some(err)),
        }
    }

    Err(unsuccessful
        .or(io_error)
        .expect("successful cases don't get here"))
}
```
which does not wait for the child to finish. Error handling could be completely abandoned in this case, placing the burden on the end user.

I am eager to know what you think about how this could be approached, or whether this should be a part of the `open` crate at all.

**Comment by Byron** [comment] 2022-06-09 23:24
Thanks a lot for the elaborate description for the problem: I wasn't aware!

Since I am working no MacOS the core assumption would be that all implementations work like they do there which is the exact behaviour you are describing. Yes, on MacOS `open` automatically detaches the child process so things like opening a PDF work naturally without blocking the caller.

As a matter of fact, this behaviour is only happening on linux, and can't be reproduced on Windows either. I think this makes it safe to say that an implementation for linux that doesn't block is what we should aim for, without introducing a new function even. A PR would be very welcome!

**Comment by kirusfg** [comment] 2022-06-10 13:47
Before making any changes, we should definitely confirm that this behavior is indeed specific to Linux.

Currently, all of the platforms use the same Command extension (except Windows), namely [`output_stderr`](https://github.com/Byron/open-rs/blob/bf6e99cb578cd3c90eed3ff4fddd712b26982e21/src/lib.rs#L185-L211). While tools like `xdg-open` and `gio open` - the alternatives of `open` from MacOS - work as expected in a terminal, the child process is not being detached when using the library.

My question is whether you have tested this in a terminal, or by actually using `open::that` with, say, a PDF file. If it is the latter, I will proceed with the patch!

**Comment by rostamn739** [comment] 2022-06-10 18:13
I have tested the form proposed by issue author:

```rust
let result = Command::new(command).args(*args).spawn();

            match result {
                Ok(_) => return Ok(()),
                Err(err) => io_error = io_error.or(Some(err)),
            }
```
It does indeed work on Linux similar to other OS-es (i.e. no wait for completion)

Otherwise, with current code when I run `cargo run -- somefile.pdf` it show a defunct (zombie) process of `xdg-open` executable and the parent process is shown (in GDB) stuck in `output_stderr` in a read call

**Comment by Byron** [comment] 2022-06-11 00:39
Thanks for trying it out!

I could also reproduce that the proposed code works as advertised, but couldn't see any zombie processes neither with the old nor with the new code. Probably I am missing something, but if not I'd be happy to see a PR that incorporates the proposed changes to the `open::that(…)` function for unix systems.

**Comment by kirusfg** [comment] 2022-06-11 08:05
> the parent process is shown (in GDB) stuck in `output_stderr` in a read call

But you are not calling `output_stderr`, instead just `spawn`ing a child process and detaching it. I am confused here, because for me, there are no `xdg-open` processes running, and the PDF viewer is correctly detached - precisely as @Byron reports.

**Comment by kirusfg** [comment] 2022-06-11 08:11
The issue is, without waiting on the child process to finish, there is no way to know whether the XDG opener has succeeded opening the file, and the behavior is the following:

```plain
$ cargo run -- /path/to/unknown/file/format
Opened '/path/to/unknown/file/format' successfully.
gio: file:///path/to/unknown/file/format: No application is registered as handling this file
```

While I am OK with that, the majority of people using this crate would definitely want this to be more robust. Suggestions will be appreciated!

**Comment by Byron** [comment] 2022-06-11 09:42
I see the problem, and it's indeed the reason the special handling around stderr was implemented.
Now I wonder if it's worth researching if all programs are similar in their blocking behaviour, and then cater to them accordingly.

My hope is that most programs here report errors in opening the program with a status code so that blocking reads aren't necessary. All this sounds like a bit of work and I think the value added by this PR already makes it worth merging even though it breaks some of the error handling.

Looking at it more closely, even on MacOS there is such `stderr` based error handling, and it's solely to provide additional error information as we always assume the launcher exists with non-zero to indicate failure. To me this looks like as long as we find a way to wait for the status in a non-blocking fashion, there should be no problem. And the latter should happen automatically of we don't try to read from `stderr` if there is none.

To sum it up, maybe it's worth a shot for you:

- remove obtaining any stderr from the launcher
- wait for the launcher to return like before

Even with xdg-open this worked fine. Here is the patch I used for testing, it needs more work to remove all the extra bits which aren't needed anymore.

```patch
diff --git a/src/lib.rs b/src/lib.rs
index 695b725..1ab9eaf 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -187,24 +187,13 @@ impl CommandExt for Command {
         let mut process = self
             .stdin(Stdio::null())
             .stdout(Stdio::null())
-            .stderr(Stdio::piped())
+            .stderr(Stdio::null())
             .spawn()?;
 
-        // Consume all stderr - it's open just for a few programs which can't handle it being closed.
-        use std::io::Read;
-        let mut stderr = vec![0; 256];
-        let mut stderr_src = process.stderr.take().expect("piped stderr");
-
-        let len = stderr_src.read(&mut stderr).unwrap_or(0);
-        stderr.truncate(len);
-
-        // consume the rest to avoid blocking
-        std::io::copy(&mut stderr_src, &mut std::io::sink()).ok();
-
         let status = process.wait()?;
         Ok(Output {
             status,
-            stderr,
+            stderr: vec![],
             stdout: vec![],
         })
     }
```

The result would be a new major release.

**Comment by Byron** [comment] 2022-06-12 01:37
I am closing this as the issue can't be reproduced anymore in [the latest release](https://github.com/Byron/open-rs/releases/tag/v3.0.0). Thanks everyone for their involvement!

Please let me know if there is anything else.

**Closed by Byron** 2022-06-12 01:37 UTC
Labels: bug
